[package]
name = "rss"
version = "1.1.0"
authors = ["James Hurst <jh.jameshurst@gmail.com>", "Corey Farwell <coreyf@rwell.org>", "Chris Palmer <pennstate5013@gmail.com>"]
description = "Library for serializing the RSS web content syndication format"
repository = "https://github.com/rust-syndication/rss"
documentation = "https://docs.rs/rss/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["rss", "feed", "parser", "parsing"]
include = ["src/*", "Cargo.toml", "LICENSE-MIT", "LICENSE-APACHE", "README.md"]

[features]
from_url = ["reqwest"]
validation = ["chrono", "url", "mime"]

[dependencies]
quick-xml = "0.10.0"
derive_builder = "0.5"
chrono = {version = "0.4", optional = true }
url = { version = "1.4", optional = true }
mime = { version = "0.3", optional = true }
reqwest = { version = "0.6", optional = true }
